### ISSUE TITLE
Short Hop!

### ISSUE THREAD

**Issue by cresse** [VRushLP/RigorMortisGame#1]
Adjust knight.js to only have upward momentum as long as 'w' is held

**Comment by tjsg1992** [comment]
Pretty sure we can solve this by:
1. Setting the jump velocity to reach an adequate short jump height
2. If the player is holding up while the knight's velocity is negative (i.e. knight is rising upwards), then decrease the velocity by some magnitude smaller than gravity's, thus decreasing your downwards acceleration. This would allow you to rise higher than normal if you are holding up, but not affect how you fall.

**Comment by tjsg1992** [comment]
Added with branch short-hop
