### ISSUE TITLE
Spikes and Falling Ball enemies

### ISSUE THREAD

**Issue by cresse** [VRushLP/RigorMortisGame#105]
spikes kill whatever touches them. both enemies and knight.
iron balls start high and drop down. after one falls, another starts dropping from the start point in the same place. does damage, but not instant kill like the spikes.

**Comment by khoadoan91** [comment]
I think I'll finish this task on the "ironball-spike" branch. I need someone to look at and check the result. Also, I made the dropping ball deal damage to enemies as well. Let me know if you see any issue
