### ISSUE TITLE
(Minimum) Standardizing Knight Animations for the game

### ISSUE THREAD

**Issue by cresse** [VRushLP/RigorMortisGame#12]
Making sure the Knight's position is retained between animations. Some are taller than others, some wider. We want to make sure the Knight doesn't get stuck in a wall because he attacked into a wall or something.

This has a lot more to do with me completing knight animations. Let me know if you guys have suggestions on how to handle this.

**Comment by tjsg1992** [comment]
I think Ian has accomplished this?
