### ISSUE TITLE
(Minimum Deliverable) Add Normal Skeleton Enemies (FINISHED)

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#21]

**Comment by tjsg1992** [comment]
Skeletons are now spawnable and do damage to the player upon collision. Still need basic A.I. implementation.

**Comment by VRushLP** [comment]
A quick rundown of the current skeleton AI:
if a skeleton is currently in it's invincibility window, it will count down to become damageable again.
Then they check to see if they still have above 0 health (This should be moved to when they take damage)
Next, Skeletons attempt to fall. They build momentum in a way similar to the Knight.
Skeletons then check to see if they are confused. If a skeleton is confused, they stand still and don't do any math until they are done being confused.
If the skeleton is not confused, they will check to see if the player is jumping or falling
If that's the case, they will then calculate the knight's center point (The knight should probably do this on it's update) and their own center point. Next, they calculate the vertical distance between those two points.
If it's between 0 and 250 (The knight's center point is 5px below a skeletons), then the skeleton will check to see if it's close enough horizontally to chase you.
If you're within the Attention Distance (400px), the skeleton will attempt to run to the last x coordinate it saw you at. When they get there, they stand still again.
If for some reason a Skeleton can't reach you (Maybe it detected you through a wall) it will run in place against the wall until you learn your lesson.

**Comment by VRushLP** [comment]
This issue should be considered closed. I'm leaving it up as a reference for anyone who wants to see how the skeleton AI works.

**Comment by tjsg1992** [comment]
I'm going to go ahead and close this. You can still access it by browsing closed issues.
