### ISSUE TITLE
(STRETCH) Add Stairs and/or Sloped Surfaces

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#23]

**Comment by tjsg1992** [comment]
This will be fairly difficult to implement, so I wouldn't base any level design around it yet.

**Comment by VRushLP** [comment]
This should be considered a stretch feature.

**Comment by tjsg1992** [comment]
Fair enough. But I think I may have just figured out a fairly simple implementation. I'll assign this to myself for now until it does/doesn't pan out.

**Comment by tjsg1992** [comment]
Neeeeeeeeeeeevermind.
