### ISSUE TITLE
Add Moving Platforms

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#24]
1. Vertical
2. Horizontal
3. Generate with variable lengths

**Comment by tjsg1992** [comment]
I'm probably going to be working on this for a bit. I'm planning to partially rewrite animation.js so that it supports the combination of several animations in one frame. So a platform animation could consist of three static blocks side-by-side. This would lead to less potential problems with moving platforms, and further optimize collision detection when it comes to long walls/floors.

**Comment by tjsg1992** [comment]
I'm going to break this down into two parts. The first will be its own branch, multiframe-animations. I'll make a pull request for that one on its own because its a fairly significant change that I want to make sure that everybody is okay with before I go forward.

**Comment by cresse** [comment]
This sounds great, but I'm not totally sure I grasp the breadth of what you're saying you'll do. Still, it sounds like a positive change and you've brought a bunch of them to the table already so I'm on board.

**Comment by tjsg1992** [comment]
So after some rethinking, I'm changing directions.
The original idea was to try to reduce the number of animations that needed to be drawn to the screen by as much as possible, and combining them accordingly. However, it turns out that the draw time this saves is absolutely trivial compared to other techniques such as drawing only where the camera is. Furthermore, by keeping individual animations as small as possible, this actually helps camera drawing optimization.

The effect this could have on collision detection time would still be something to consider, but that entails merging entities, not necessarily animations. And it's not very high priority right now, so I'll come back to that later.

As such, I'm going to find a way to implement the changes just focused around ideas like moving platforms for now.

**Comment by khoadoan91** [comment]
No worry about that, Taylor.

I've already done optimizing the drawing to the screen and it seems true as what you said. It does not save much time for cpu compared to the original drawing. I don't know if there are some issues in my code. But it will be great if you can help me point out.
