### ISSUE TITLE
(Minimum Deliverable) Add Forward Sword Swing

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#27]

**Comment by tjsg1992** [comment]
- Forward swing can now be activated by space.
- Cannot be performed while airborne.
- Locks you in place until the animation finishes.
- Creates a sword hitbox that damages enemies.

Todo:
- Fix animation appearance. You currently swing from inside the ground, and the left swing looks really  off because of how the animation is drawn. Probably need to add a field inside of animation that indicates how much you want to offset the animation by.
- Swinging needs extensive testing with its relation to movement (pressing down before/while swinging, swinging while being pushed by a platform, taking damage and getting knockbacked while swinging, etc.)
- This is the first animation that does not loop, and where in-game events (i.e. locked movement, sword hitbox) are entirely dependent upon its length. Look into some way to formalize the adaptation of an animation's duration into an entity's update loop. Right now it's just guesswork, and feels somewhat off accordingly.

**Comment by VRushLP** [comment]
The current design for the weapon swing and movement is that you can't move while swinging anyway, so that's not a problem. Whether or not you can attacking while jumping is still to be decided.

Personally I don't like that the action key is space. It feels like there's too much emphasis on the left hand.

**Comment by tjsg1992** [comment]
Yeah, feel free to move it to whichever key. Using space was a pretty arbitrary decision.
