### ISSUE TITLE
(Minimum) Taking damage

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#28]
1. For Knight
2. For enemies

**Comment by VRushLP** [comment]
Entities should also be knocked back on taking damage in general.

**Comment by tjsg1992** [comment]
I'm going to work on this tonight to add on-collision damage (i.e. if you run into a skeleton)

**Comment by tjsg1992** [comment]
Added:
- Running into a skeleton knocks you back and you take damage.
- Pressing space swings your sword and creates a sword hitbox
- Any enemy within that hitbox takes damage.
- When a player or skeleton takes damage, they are granted temporary invulnerability.
- When a skeleton's health is 0, it despawns
- When a player's health is 0, it respawns

Todo:
- Add horizontal acceleration to knight so that knockback looks much more clean
- Have knockback move you in the opposite direction of where you're hit, not just the opposite direction of the way you are facing
- Despawning needs to be redone (i.e. implement RemoveFromWorld)

**Comment by tjsg1992** [comment]
I'm going to tackle horizontal acceleration while refactoring knight.

**Comment by VRushLP** [comment]
Standing still causes undesired behavior with collision.

**Comment by tjsg1992** [comment]
All done except for directional knockback. Going to open a new issue for that one.
