### ISSUE TITLE
Refactor GameEngine.requestMove

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#48]
requestMove() is getting too complex. Divide it into the following methods:
- requestMove()
- findNearestCollision()
- refocusCamera()
- checkPlayerRespawn()

Bonus:
Write findNearestCollision() so that it takes parameters indicating in which direction(s) to check, and then have checkBottomCollision() and checkTopCollision() utilize that. In doing so, make sure that findNearestCollision() returns an array of all entities that are of equal minimal closeness (so that a platform can call it to drag several entities that are resting directly on top of it, and not just the first one it finds)

**Comment by VRushLP** [comment]
I can look into doing this starting Tuesday.
