### ISSUE TITLE
Implement Forest Boss background

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#92]
- ~~Add background~~
- ~~Add Statute~~
- Have the statue transition between states based on forest boss phases

The Statue should be in forest-boss.js so that it can easily be changed as the forest boss changes phases. Additionally, it would probably be helpful to add a "change phase" method to do this work in.

**Comment by VRushLP** [comment]
I'm gonna call this finished for now. We can make it less rigid if we keep working on the game after the quarter ends.
